// Generated by scripts/flipwarp-extract-extensions.js from the extensions'
// own block definitions. Do not edit by hand — re-run the script.
//
// Extension block names are written with their extension in front, so
// pen.penDown() can never collide with a core block or another
// extension's block of the same name.

export const EXTENSION_BLOCKS = {
    pen_clear: { kind: 'statement', name: 'pen.eraseAll', args: [], extension: true },
    pen_stamp: { kind: 'statement', name: 'pen.stamp', args: [], extension: true },
    pen_penDown: { kind: 'statement', name: 'pen.penDown', args: [], extension: true },
    pen_penUp: { kind: 'statement', name: 'pen.penUp', args: [], extension: true },
    pen_setPenColorToColor: { kind: 'statement', name: 'pen.setPenColorTo', args: ["COLOR"], extension: true },
    pen_changePenColorParamBy: { kind: 'statement', name: 'pen.changePenBy', args: ["COLOR_PARAM","VALUE"], menu: {"COLOR_PARAM":"pen_menu_colorParam"}, extension: true },
    pen_setPenColorParamTo: { kind: 'statement', name: 'pen.setPenTo', args: ["COLOR_PARAM","VALUE"], menu: {"COLOR_PARAM":"pen_menu_colorParam"}, extension: true },
    pen_changePenSizeBy: { kind: 'statement', name: 'pen.changePenSizeBy', args: ["SIZE"], extension: true },
    pen_setPenSizeTo: { kind: 'statement', name: 'pen.setPenSizeTo', args: ["SIZE"], extension: true },
    pen_setPenShadeToNumber: { kind: 'statement', name: 'pen.setPenShadeTo', args: ["SHADE"], extension: true },
    pen_changePenShadeBy: { kind: 'statement', name: 'pen.changePenShadeBy', args: ["SHADE"], extension: true },
    pen_setPenHueToNumber: { kind: 'statement', name: 'pen.setPenHueToNumber', args: ["HUE"], extension: true },
    pen_changePenHueBy: { kind: 'statement', name: 'pen.changePenColorBy', args: ["HUE"], extension: true },
    music_playDrumForBeats: { kind: 'statement', name: 'music.playDrumForBeats', args: ["DRUM","BEATS"], menu: {"DRUM":"music_menu_DRUM"}, extension: true },
    music_midiPlayDrumForBeats: { kind: 'statement', name: 'music.midiPlayDrumForBeats', args: ["DRUM","BEATS"], menu: {"DRUM":"music_menu_DRUM"}, extension: true },
    music_restForBeats: { kind: 'statement', name: 'music.restForBeats', args: ["BEATS"], extension: true },
    music_playNoteForBeats: { kind: 'statement', name: 'music.playNoteForBeats', args: ["NOTE","BEATS"], extension: true },
    music_setInstrument: { kind: 'statement', name: 'music.setInstrumentTo', args: ["INSTRUMENT"], menu: {"INSTRUMENT":"music_menu_INSTRUMENT"}, extension: true },
    music_midiSetInstrument: { kind: 'statement', name: 'music.midiSetInstrument', args: ["INSTRUMENT"], extension: true },
    music_setTempo: { kind: 'statement', name: 'music.setTempoTo', args: ["TEMPO"], extension: true },
    music_changeTempo: { kind: 'statement', name: 'music.changeTempoBy', args: ["TEMPO"], extension: true },
    music_getTempo: { kind: 'reporter', name: 'music.tempo', args: [], extension: true },
    text2speech_speakAndWait: { kind: 'statement', name: 'text2speech.speak', args: ["WORDS"], extension: true },
    text2speech_setVoice: { kind: 'statement', name: 'text2speech.setVoiceTo', args: ["VOICE"], menu: {"VOICE":"text2speech_menu_voices"}, extension: true },
    text2speech_setLanguage: { kind: 'statement', name: 'text2speech.setLanguageTo', args: ["LANGUAGE"], menu: {"LANGUAGE":"text2speech_menu_languages"}, extension: true },
    translate_getTranslate: { kind: 'reporter', name: 'translate.translateTo', args: ["WORDS","LANGUAGE"], menu: {"LANGUAGE":"translate_menu_languages"}, extension: true },
    translate_getViewerLanguage: { kind: 'reporter', name: 'translate.language', args: [], extension: true },
    videoSensing_whenMotionGreaterThan: { kind: 'hat', name: 'videoSensing.whenVideoMotion', args: ["REFERENCE"], extension: true },
    videoSensing_videoOn: { kind: 'reporter', name: 'videoSensing.videoOn', args: ["ATTRIBUTE","SUBJECT"], menu: {"ATTRIBUTE":"videoSensing_menu_ATTRIBUTE","SUBJECT":"videoSensing_menu_SUBJECT"}, extension: true },
    videoSensing_videoToggle: { kind: 'statement', name: 'videoSensing.turnVideo', args: ["VIDEO_STATE"], menu: {"VIDEO_STATE":"videoSensing_menu_VIDEO_STATE"}, extension: true },
    videoSensing_setVideoTransparency: { kind: 'statement', name: 'videoSensing.setVideoTransparencyTo', args: ["TRANSPARENCY"], extension: true },
    makeymakey_whenMakeyKeyPressed: { kind: 'hat', name: 'makeymakey.whenKeyPressed', args: ["KEY"], menu: {"KEY":"makeymakey_menu_KEY"}, extension: true },
    makeymakey_whenCodePressed: { kind: 'hat', name: 'makeymakey.whenPressedInOrder', args: ["SEQUENCE"], menu: {"SEQUENCE":"makeymakey_menu_SEQUENCE"}, extension: true },
    microbit_whenButtonPressed: { kind: 'hat', name: 'microbit.whenButtonPressed', args: ["BTN"], menu: {"BTN":"microbit_menu_buttons"}, extension: true },
    microbit_isButtonPressed: { kind: 'boolean', name: 'microbit.buttonPressed', args: ["BTN"], menu: {"BTN":"microbit_menu_buttons"}, extension: true },
    microbit_whenGesture: { kind: 'hat', name: 'microbit.when', args: ["GESTURE"], menu: {"GESTURE":"microbit_menu_gestures"}, extension: true },
    microbit_displaySymbol: { kind: 'statement', name: 'microbit.display', args: ["MATRIX"], extension: true },
    microbit_displayText: { kind: 'statement', name: 'microbit.displayText', args: ["TEXT"], extension: true },
    microbit_displayClear: { kind: 'statement', name: 'microbit.clearDisplay', args: [], extension: true },
    microbit_whenTilted: { kind: 'hat', name: 'microbit.whenTilted', args: ["DIRECTION"], menu: {"DIRECTION":"microbit_menu_tiltDirectionAny"}, extension: true },
    microbit_isTilted: { kind: 'boolean', name: 'microbit.tilted', args: ["DIRECTION"], menu: {"DIRECTION":"microbit_menu_tiltDirectionAny"}, extension: true },
    microbit_getTiltAngle: { kind: 'reporter', name: 'microbit.tiltAngle', args: ["DIRECTION"], menu: {"DIRECTION":"microbit_menu_tiltDirection"}, extension: true },
    microbit_whenPinConnected: { kind: 'hat', name: 'microbit.whenPinConnected', args: ["PIN"], menu: {"PIN":"microbit_menu_touchPins"}, extension: true },
    ev3_motorTurnClockwise: { kind: 'statement', name: 'ev3.motorTurnThisWayForSeconds', args: ["PORT","TIME"], menu: {"PORT":"ev3_menu_motorPorts"}, extension: true },
    ev3_motorTurnCounterClockwise: { kind: 'statement', name: 'ev3.motorTurnThatWayForSeconds', args: ["PORT","TIME"], menu: {"PORT":"ev3_menu_motorPorts"}, extension: true },
    ev3_motorSetPower: { kind: 'statement', name: 'ev3.motorSetPower', args: ["PORT","POWER"], menu: {"PORT":"ev3_menu_motorPorts"}, extension: true },
    ev3_getMotorPosition: { kind: 'reporter', name: 'ev3.motorPosition', args: ["PORT"], menu: {"PORT":"ev3_menu_motorPorts"}, extension: true },
    ev3_whenButtonPressed: { kind: 'hat', name: 'ev3.whenButtonPressed', args: ["PORT"], menu: {"PORT":"ev3_menu_sensorPorts"}, extension: true },
    ev3_whenDistanceLessThan: { kind: 'hat', name: 'ev3.whenDistance', args: ["DISTANCE"], extension: true },
    ev3_whenBrightnessLessThan: { kind: 'hat', name: 'ev3.whenBrightness', args: ["DISTANCE"], extension: true },
    ev3_buttonPressed: { kind: 'boolean', name: 'ev3.buttonPressed', args: ["PORT"], menu: {"PORT":"ev3_menu_sensorPorts"}, extension: true },
    ev3_getDistance: { kind: 'reporter', name: 'ev3.distance', args: [], extension: true },
    ev3_getBrightness: { kind: 'reporter', name: 'ev3.brightness', args: [], extension: true },
    ev3_beep: { kind: 'statement', name: 'ev3.beepNoteForSecs', args: ["NOTE","TIME"], extension: true },
    boost_motorOnFor: { kind: 'statement', name: 'boost.turnMotorForSeconds', args: ["MOTOR_ID","DURATION"], menu: {"MOTOR_ID":"boost_menu_MOTOR_ID"}, extension: true },
    boost_motorOnForRotation: { kind: 'statement', name: 'boost.turnMotorForRotations', args: ["MOTOR_ID","ROTATION"], menu: {"MOTOR_ID":"boost_menu_MOTOR_ID"}, extension: true },
    boost_motorOn: { kind: 'statement', name: 'boost.turnMotorOn', args: ["MOTOR_ID"], menu: {"MOTOR_ID":"boost_menu_MOTOR_ID"}, extension: true },
    boost_motorOff: { kind: 'statement', name: 'boost.turnMotorOff', args: ["MOTOR_ID"], menu: {"MOTOR_ID":"boost_menu_MOTOR_ID"}, extension: true },
    boost_setMotorPower: { kind: 'statement', name: 'boost.setMotorSpeedTo', args: ["MOTOR_ID","POWER"], menu: {"MOTOR_ID":"boost_menu_MOTOR_ID"}, extension: true },
    boost_setMotorDirection: { kind: 'statement', name: 'boost.setMotorDirection', args: ["MOTOR_ID","MOTOR_DIRECTION"], menu: {"MOTOR_ID":"boost_menu_MOTOR_ID","MOTOR_DIRECTION":"boost_menu_MOTOR_DIRECTION"}, extension: true },
    boost_getMotorPosition: { kind: 'reporter', name: 'boost.motorPosition', args: ["MOTOR_REPORTER_ID"], menu: {"MOTOR_REPORTER_ID":"boost_menu_MOTOR_REPORTER_ID"}, extension: true },
    boost_whenColor: { kind: 'hat', name: 'boost.whenBrickSeen', args: ["COLOR"], menu: {"COLOR":"boost_menu_COLOR"}, extension: true },
    boost_seeingColor: { kind: 'boolean', name: 'boost.seeingBrick', args: ["COLOR"], menu: {"COLOR":"boost_menu_COLOR"}, extension: true },
    boost_whenTilted: { kind: 'hat', name: 'boost.whenTilted', args: ["TILT_DIRECTION_ANY"], menu: {"TILT_DIRECTION_ANY":"boost_menu_TILT_DIRECTION_ANY"}, extension: true },
    boost_getTiltAngle: { kind: 'reporter', name: 'boost.tiltAngle', args: ["TILT_DIRECTION"], menu: {"TILT_DIRECTION":"boost_menu_TILT_DIRECTION"}, extension: true },
    boost_setLightHue: { kind: 'statement', name: 'boost.setLightColorTo', args: ["HUE"], extension: true },
    wedo2_motorOnFor: { kind: 'statement', name: 'wedo2.turnOnForSeconds', args: ["MOTOR_ID","DURATION"], menu: {"MOTOR_ID":"wedo2_menu_MOTOR_ID"}, extension: true },
    wedo2_motorOn: { kind: 'statement', name: 'wedo2.turnOn', args: ["MOTOR_ID"], menu: {"MOTOR_ID":"wedo2_menu_MOTOR_ID"}, extension: true },
    wedo2_motorOff: { kind: 'statement', name: 'wedo2.turnOff', args: ["MOTOR_ID"], menu: {"MOTOR_ID":"wedo2_menu_MOTOR_ID"}, extension: true },
    wedo2_startMotorPower: { kind: 'statement', name: 'wedo2.setPowerTo', args: ["MOTOR_ID","POWER"], menu: {"MOTOR_ID":"wedo2_menu_MOTOR_ID"}, extension: true },
    wedo2_setMotorDirection: { kind: 'statement', name: 'wedo2.setDirectionTo', args: ["MOTOR_ID","MOTOR_DIRECTION"], menu: {"MOTOR_ID":"wedo2_menu_MOTOR_ID","MOTOR_DIRECTION":"wedo2_menu_MOTOR_DIRECTION"}, extension: true },
    wedo2_setLightHue: { kind: 'statement', name: 'wedo2.setLightColorTo', args: ["HUE"], extension: true },
    wedo2_playNoteFor: { kind: 'statement', name: 'wedo2.playNoteForSeconds', args: ["NOTE","DURATION"], extension: true },
    wedo2_whenDistance: { kind: 'hat', name: 'wedo2.whenDistance', args: ["OP","REFERENCE"], menu: {"OP":"wedo2_menu_OP"}, extension: true },
    wedo2_whenTilted: { kind: 'hat', name: 'wedo2.whenTilted', args: ["TILT_DIRECTION_ANY"], menu: {"TILT_DIRECTION_ANY":"wedo2_menu_TILT_DIRECTION_ANY"}, extension: true },
    wedo2_getDistance: { kind: 'reporter', name: 'wedo2.distance', args: [], extension: true },
    wedo2_isTilted: { kind: 'boolean', name: 'wedo2.tilted', args: ["TILT_DIRECTION_ANY"], menu: {"TILT_DIRECTION_ANY":"wedo2_menu_TILT_DIRECTION_ANY"}, extension: true },
    wedo2_getTiltAngle: { kind: 'reporter', name: 'wedo2.tiltAngle', args: ["TILT_DIRECTION"], menu: {"TILT_DIRECTION":"wedo2_menu_TILT_DIRECTION"}, extension: true },
    gdxfor_whenGesture: { kind: 'hat', name: 'gdxfor.when', args: ["GESTURE"], menu: {"GESTURE":"gdxfor_menu_gestureOptions"}, extension: true },
    gdxfor_whenForcePushedOrPulled: { kind: 'hat', name: 'gdxfor.whenForceSensor', args: ["PUSH_PULL"], menu: {"PUSH_PULL":"gdxfor_menu_pushPullOptions"}, extension: true },
    gdxfor_getForce: { kind: 'reporter', name: 'gdxfor.force', args: [], extension: true },
    gdxfor_whenTilted: { kind: 'hat', name: 'gdxfor.whenTilted', args: ["TILT"], menu: {"TILT":"gdxfor_menu_tiltAnyOptions"}, extension: true },
    gdxfor_isTilted: { kind: 'boolean', name: 'gdxfor.tilted', args: ["TILT"], menu: {"TILT":"gdxfor_menu_tiltAnyOptions"}, extension: true },
    gdxfor_getTilt: { kind: 'reporter', name: 'gdxfor.tiltAngle', args: ["TILT"], menu: {"TILT":"gdxfor_menu_tiltOptions"}, extension: true },
    gdxfor_isFreeFalling: { kind: 'boolean', name: 'gdxfor.falling', args: [], extension: true },
    gdxfor_getSpinSpeed: { kind: 'reporter', name: 'gdxfor.spinSpeed', args: ["DIRECTION"], menu: {"DIRECTION":"gdxfor_menu_axisOptions"}, extension: true },
    gdxfor_getAcceleration: { kind: 'reporter', name: 'gdxfor.acceleration', args: ["DIRECTION"], menu: {"DIRECTION":"gdxfor_menu_axisOptions"}, extension: true },
    flipwarpDialogue_use: { kind: 'statement', name: 'dialogue.useConversation', args: ["TEXT"], extension: true },
    flipwarpDialogue_goTo: { kind: 'statement', name: 'dialogue.goToPart', args: ["NAME"], extension: true },
    flipwarpDialogue_says: { kind: 'reporter', name: 'dialogue.whatIsSaidHere', args: [], extension: true },
    flipwarpDialogue_replyCount: { kind: 'reporter', name: 'dialogue.numberOfReplies', args: [], extension: true },
    flipwarpDialogue_reply: { kind: 'reporter', name: 'dialogue.reply', args: ["N"], extension: true },
    flipwarpDialogue_choose: { kind: 'statement', name: 'dialogue.chooseReply', args: ["N"], extension: true },
    flipwarpDialogue_here: { kind: 'reporter', name: 'dialogue.partIAmAt', args: [], extension: true },
    flipwarpDialogue_isEnd: { kind: 'boolean', name: 'dialogue.conversationOver', args: [], extension: true },
    flipwarpDialogue_partNames: { kind: 'reporter', name: 'dialogue.allPartNames', args: [], extension: true },
    flipwarpDialogue_problems: { kind: 'reporter', name: 'dialogue.problemsWithTheConversation', args: [], extension: true },
    flipwarpNear_rebuild: { kind: 'statement', name: 'near.noteWhereEverySpriteIs', args: [], extension: true },
    flipwarpNear_setSquare: { kind: 'statement', name: 'near.useSquaresStepsAcross', args: ["SIZE"], extension: true },
    flipwarpNear_countNear: { kind: 'reporter', name: 'near.howManyWithinOfMe', args: ["RANGE"], extension: true },
    flipwarpNear_anyNear: { kind: 'boolean', name: 'near.anythingWithinOfMe', args: ["RANGE"], extension: true },
    flipwarpNear_nearestDistance: { kind: 'reporter', name: 'near.distanceToTheNearestWithin', args: ["RANGE"], extension: true },
    flipwarpNear_nearestDirection: { kind: 'reporter', name: 'near.directionOfTheNearestWithin', args: ["RANGE"], extension: true },
    flipwarpNear_countNearPoint: { kind: 'reporter', name: 'near.howManyWithinOfXY', args: ["RANGE","X","Y"], extension: true },
    flipwarpNear_noted: { kind: 'reporter', name: 'near.spritesNoted', args: [], extension: true },
    flipwarpNear_looked: { kind: 'reporter', name: 'near.spritesLookedAtLastTime', args: [], extension: true },
    flipwarpPathfinding_setSquare: { kind: 'statement', name: 'route.useSquaresStepsAcross', args: ["SIZE"], extension: true },
    flipwarpPathfinding_clearWalls: { kind: 'statement', name: 'route.clearAllWalls', args: [], extension: true },
    flipwarpPathfinding_blockAt: { kind: 'statement', name: 'route.putAWallAtXY', args: ["X","Y"], extension: true },
    flipwarpPathfinding_unblockAt: { kind: 'statement', name: 'route.clearTheWallAtXY', args: ["X","Y"], extension: true },
    flipwarpPathfinding_isBlocked: { kind: 'boolean', name: 'route.wallAtXY', args: ["X","Y"], extension: true },
    flipwarpPathfinding_findFromMe: { kind: 'statement', name: 'route.findARouteFromMeToXY', args: ["X","Y"], extension: true },
    flipwarpPathfinding_find: { kind: 'statement', name: 'route.findARouteFromXYToXY', args: ["FX","FY","TX","TY"], extension: true },
    flipwarpPathfinding_found: { kind: 'boolean', name: 'route.routeFound', args: [], extension: true },
    flipwarpPathfinding_steps: { kind: 'reporter', name: 'route.stepsInTheRoute', args: [], extension: true },
    flipwarpPathfinding_stepX: { kind: 'reporter', name: 'route.xOfStep', args: ["N"], extension: true },
    flipwarpPathfinding_stepY: { kind: 'reporter', name: 'route.yOfStep', args: ["N"], extension: true },
    flipwarpPathfinding_goToStep: { kind: 'statement', name: 'route.goToStepOfTheRoute', args: ["N"], extension: true },
    flipwarpPathfinding_directionOfNextStep: { kind: 'reporter', name: 'route.directionOfTheNextStepFromMe', args: [], extension: true },
    flipwarpPathfinding_squaresLookedAt: { kind: 'reporter', name: 'route.squaresLookedAt', args: [], extension: true },
    flipwarpRecordReplay_startRecording: { kind: 'statement', name: 'replay.startRecordingInput', args: [], extension: true },
    flipwarpRecordReplay_stopRecording: { kind: 'statement', name: 'replay.stopRecording', args: [], extension: true },
    flipwarpRecordReplay_isRecording: { kind: 'boolean', name: 'replay.recording', args: [], extension: true },
    flipwarpRecordReplay_play: { kind: 'statement', name: 'replay.playTheRecording', args: [], extension: true },
    flipwarpRecordReplay_playAndWait: { kind: 'statement', name: 'replay.playTheRecordingAndWait', args: [], extension: true },
    flipwarpRecordReplay_stopPlaying: { kind: 'statement', name: 'replay.stopPlaying', args: [], extension: true },
    flipwarpRecordReplay_isPlaying: { kind: 'boolean', name: 'replay.playing', args: [], extension: true },
    flipwarpRecordReplay_setSpeed: { kind: 'statement', name: 'replay.playAtTimesSpeed', args: ["SPEED"], extension: true },
    flipwarpRecordReplay_length: { kind: 'reporter', name: 'replay.recordingLengthInSeconds', args: [], extension: true },
    flipwarpRecordReplay_count: { kind: 'reporter', name: 'replay.thingsInTheRecording', args: [], extension: true },
    flipwarpRecordReplay_asText: { kind: 'reporter', name: 'replay.recordingAsText', args: [], extension: true },
    flipwarpRecordReplay_fromText: { kind: 'statement', name: 'replay.useRecording', args: ["TEXT"], extension: true },
    flipwarpRecordReplay_clear: { kind: 'statement', name: 'replay.clearTheRecording', args: [], extension: true },
    flipwarpSaveSlots_save: { kind: 'statement', name: 'saveSlots.saveAsInSlot', args: ["VALUE","NAME","SLOT"], extension: true },
    flipwarpSaveSlots_load: { kind: 'reporter', name: 'saveSlots.fromSlot', args: ["NAME","SLOT"], extension: true },
    flipwarpSaveSlots_has: { kind: 'boolean', name: 'saveSlots.slotHas', args: ["SLOT","NAME"], extension: true },
    flipwarpSaveSlots_saveList: { kind: 'statement', name: 'saveSlots.saveListAsInSlot', args: ["LIST","NAME","SLOT"], extension: true },
    flipwarpSaveSlots_loadList: { kind: 'statement', name: 'saveSlots.loadFromSlotIntoList', args: ["NAME","SLOT","LIST"], extension: true },
    flipwarpSaveSlots_namesIn: { kind: 'reporter', name: 'saveSlots.namesSavedInSlot', args: ["SLOT"], extension: true },
    flipwarpSaveSlots_slots: { kind: 'reporter', name: 'saveSlots.allSlots', args: [], extension: true },
    flipwarpSaveSlots_slotExists: { kind: 'boolean', name: 'saveSlots.slotExists', args: ["SLOT"], extension: true },
    flipwarpSaveSlots_forget: { kind: 'statement', name: 'saveSlots.forgetInSlot', args: ["NAME","SLOT"], extension: true },
    flipwarpSaveSlots_deleteSlot: { kind: 'statement', name: 'saveSlots.deleteSlot', args: ["SLOT"], extension: true },
    flipwarpSaveSlots_deleteEverything: { kind: 'statement', name: 'saveSlots.deleteEverySlot', args: [], extension: true },
    flipwarpSaveSlots_sizeOf: { kind: 'reporter', name: 'saveSlots.sizeOfSlotInCharacters', args: ["SLOT"], extension: true },
    flipwarpSaveSlots_lastProblem: { kind: 'reporter', name: 'saveSlots.lastSaveProblem', args: [], extension: true },
    flipwarpTilemap_load: { kind: 'statement', name: 'tiles.useMap', args: ["MAP"], extension: true },
    flipwarpTilemap_setTileSize: { kind: 'statement', name: 'tiles.makeEachTileStepsAcross', args: ["SIZE"], extension: true },
    flipwarpTilemap_setSolid: { kind: 'statement', name: 'tiles.treatAsWalls', args: ["CHARS"], extension: true },
    flipwarpTilemap_tileAtColumnRow: { kind: 'reporter', name: 'tiles.tileAtColumnRow', args: ["COL","ROW"], extension: true },
    flipwarpTilemap_tileAt: { kind: 'reporter', name: 'tiles.tileAtXY', args: ["X","Y"], extension: true },
    flipwarpTilemap_tileUnderMe: { kind: 'reporter', name: 'tiles.tileUnderMe', args: [], extension: true },
    flipwarpTilemap_setTile: { kind: 'statement', name: 'tiles.putAtColumnRow', args: ["TILE","COL","ROW"], extension: true },
    flipwarpTilemap_isWallAt: { kind: 'boolean', name: 'tiles.wallAtXY', args: ["X","Y"], extension: true },
    flipwarpTilemap_wouldHitWall: { kind: 'boolean', name: 'tiles.wouldIHitAWallMovingAcrossAndUp', args: ["DX","DY"], extension: true },
    flipwarpTilemap_slideBy: { kind: 'statement', name: 'tiles.moveAcrossAndUpStoppingAtWalls', args: ["DX","DY"], extension: true },
    flipwarpTilemap_tileCount: { kind: 'reporter', name: 'tiles.numberOfTiles', args: [], extension: true },
    flipwarpTilemap_goToTile: { kind: 'statement', name: 'tiles.goToTheMiddleOfTile', args: ["N"], extension: true },
    flipwarpTilemap_tileNumber: { kind: 'reporter', name: 'tiles.tileNumber', args: ["N"], extension: true },
    flipwarpTilemap_columns: { kind: 'reporter', name: 'tiles.columns', args: [], extension: true },
    flipwarpTilemap_rowCount: { kind: 'reporter', name: 'tiles.rows', args: [], extension: true },
    flipwarpTilemap_firstX: { kind: 'reporter', name: 'tiles.xOfTheFirst', args: ["TILE"], extension: true },
    flipwarpTilemap_firstY: { kind: 'reporter', name: 'tiles.yOfTheFirst', args: ["TILE"], extension: true },
    flipwarpTilemap_countOf: { kind: 'reporter', name: 'tiles.howMany', args: ["TILE"], extension: true },
    flipwarpTilemap_asText: { kind: 'reporter', name: 'tiles.theMapAsText', args: [], extension: true },
    flipwarpTilemap_sendWallsToPathfinding: { kind: 'statement', name: 'tiles.giveTheWallsToPathfinding', args: [], extension: true },
};

export const EXTENSION_INPUT_SHADOWS = {
    "pen_setPenColorToColor": {
        "COLOR": "colour_picker"
    },
    "pen_changePenColorParamBy": {
        "VALUE": "math_number"
    },
    "pen_setPenColorParamTo": {
        "VALUE": "math_number"
    },
    "pen_changePenSizeBy": {
        "SIZE": "math_number"
    },
    "pen_setPenSizeTo": {
        "SIZE": "math_number"
    },
    "pen_setPenShadeToNumber": {
        "SHADE": "math_number"
    },
    "pen_changePenShadeBy": {
        "SHADE": "math_number"
    },
    "pen_setPenHueToNumber": {
        "HUE": "math_number"
    },
    "pen_changePenHueBy": {
        "HUE": "math_number"
    },
    "music_playDrumForBeats": {
        "BEATS": "math_number"
    },
    "music_midiPlayDrumForBeats": {
        "BEATS": "math_number"
    },
    "music_restForBeats": {
        "BEATS": "math_number"
    },
    "music_playNoteForBeats": {
        "NOTE": "note",
        "BEATS": "math_number"
    },
    "music_midiSetInstrument": {
        "INSTRUMENT": "math_number"
    },
    "music_setTempo": {
        "TEMPO": "math_number"
    },
    "music_changeTempo": {
        "TEMPO": "math_number"
    },
    "text2speech_speakAndWait": {
        "WORDS": "text"
    },
    "translate_getTranslate": {
        "WORDS": "text"
    },
    "videoSensing_whenMotionGreaterThan": {
        "REFERENCE": "math_number"
    },
    "videoSensing_setVideoTransparency": {
        "TRANSPARENCY": "math_number"
    },
    "microbit_displaySymbol": {
        "MATRIX": "matrix"
    },
    "microbit_displayText": {
        "TEXT": "text"
    },
    "ev3_motorTurnClockwise": {
        "TIME": "math_number"
    },
    "ev3_motorTurnCounterClockwise": {
        "TIME": "math_number"
    },
    "ev3_motorSetPower": {
        "POWER": "math_number"
    },
    "ev3_whenDistanceLessThan": {
        "DISTANCE": "math_number"
    },
    "ev3_whenBrightnessLessThan": {
        "DISTANCE": "math_number"
    },
    "ev3_beep": {
        "NOTE": "note",
        "TIME": "math_number"
    },
    "boost_motorOnFor": {
        "DURATION": "math_number"
    },
    "boost_motorOnForRotation": {
        "ROTATION": "math_number"
    },
    "boost_setMotorPower": {
        "POWER": "math_number"
    },
    "boost_setLightHue": {
        "HUE": "math_number"
    },
    "wedo2_motorOnFor": {
        "DURATION": "math_number"
    },
    "wedo2_startMotorPower": {
        "POWER": "math_number"
    },
    "wedo2_setLightHue": {
        "HUE": "math_number"
    },
    "wedo2_playNoteFor": {
        "NOTE": "math_number",
        "DURATION": "math_number"
    },
    "wedo2_whenDistance": {
        "REFERENCE": "math_number"
    },
    "flipwarpDialogue_use": {
        "TEXT": "text"
    },
    "flipwarpDialogue_goTo": {
        "NAME": "text"
    },
    "flipwarpDialogue_reply": {
        "N": "math_number"
    },
    "flipwarpDialogue_choose": {
        "N": "math_number"
    },
    "flipwarpNear_setSquare": {
        "SIZE": "math_number"
    },
    "flipwarpNear_countNear": {
        "RANGE": "math_number"
    },
    "flipwarpNear_anyNear": {
        "RANGE": "math_number"
    },
    "flipwarpNear_nearestDistance": {
        "RANGE": "math_number"
    },
    "flipwarpNear_nearestDirection": {
        "RANGE": "math_number"
    },
    "flipwarpNear_countNearPoint": {
        "RANGE": "math_number",
        "X": "math_number",
        "Y": "math_number"
    },
    "flipwarpPathfinding_setSquare": {
        "SIZE": "math_number"
    },
    "flipwarpPathfinding_blockAt": {
        "X": "math_number",
        "Y": "math_number"
    },
    "flipwarpPathfinding_unblockAt": {
        "X": "math_number",
        "Y": "math_number"
    },
    "flipwarpPathfinding_isBlocked": {
        "X": "math_number",
        "Y": "math_number"
    },
    "flipwarpPathfinding_findFromMe": {
        "X": "math_number",
        "Y": "math_number"
    },
    "flipwarpPathfinding_find": {
        "FX": "math_number",
        "FY": "math_number",
        "TX": "math_number",
        "TY": "math_number"
    },
    "flipwarpPathfinding_stepX": {
        "N": "math_number"
    },
    "flipwarpPathfinding_stepY": {
        "N": "math_number"
    },
    "flipwarpPathfinding_goToStep": {
        "N": "math_number"
    },
    "flipwarpRecordReplay_setSpeed": {
        "SPEED": "math_number"
    },
    "flipwarpRecordReplay_fromText": {
        "TEXT": "text"
    },
    "flipwarpSaveSlots_save": {
        "VALUE": "text",
        "NAME": "text",
        "SLOT": "text"
    },
    "flipwarpSaveSlots_load": {
        "NAME": "text",
        "SLOT": "text"
    },
    "flipwarpSaveSlots_has": {
        "SLOT": "text",
        "NAME": "text"
    },
    "flipwarpSaveSlots_saveList": {
        "LIST": "text",
        "NAME": "text",
        "SLOT": "text"
    },
    "flipwarpSaveSlots_loadList": {
        "NAME": "text",
        "SLOT": "text",
        "LIST": "text"
    },
    "flipwarpSaveSlots_namesIn": {
        "SLOT": "text"
    },
    "flipwarpSaveSlots_slotExists": {
        "SLOT": "text"
    },
    "flipwarpSaveSlots_forget": {
        "NAME": "text",
        "SLOT": "text"
    },
    "flipwarpSaveSlots_deleteSlot": {
        "SLOT": "text"
    },
    "flipwarpSaveSlots_sizeOf": {
        "SLOT": "text"
    },
    "flipwarpTilemap_load": {
        "MAP": "text"
    },
    "flipwarpTilemap_setTileSize": {
        "SIZE": "math_number"
    },
    "flipwarpTilemap_setSolid": {
        "CHARS": "text"
    },
    "flipwarpTilemap_tileAtColumnRow": {
        "COL": "math_number",
        "ROW": "math_number"
    },
    "flipwarpTilemap_tileAt": {
        "X": "math_number",
        "Y": "math_number"
    },
    "flipwarpTilemap_setTile": {
        "TILE": "text",
        "COL": "math_number",
        "ROW": "math_number"
    },
    "flipwarpTilemap_isWallAt": {
        "X": "math_number",
        "Y": "math_number"
    },
    "flipwarpTilemap_wouldHitWall": {
        "DX": "math_number",
        "DY": "math_number"
    },
    "flipwarpTilemap_slideBy": {
        "DX": "math_number",
        "DY": "math_number"
    },
    "flipwarpTilemap_goToTile": {
        "N": "math_number"
    },
    "flipwarpTilemap_tileNumber": {
        "N": "math_number"
    },
    "flipwarpTilemap_firstX": {
        "TILE": "text"
    },
    "flipwarpTilemap_firstY": {
        "TILE": "text"
    },
    "flipwarpTilemap_countOf": {
        "TILE": "text"
    }
};
